services:
  terminal-profile:
    container_name: terminal-profile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules