name: Deploy to Azure VM on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent and Add Private Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.AZURE_VM_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: SSH into Azure VM and Pull Latest
        run: |
          ssh azureuser@${{ secrets.AZURE_VM_PUBLIC_IP }} << 'EOF'
            cd ~/terminal-profile
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
          EOF